# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0279cb23a0aca2f2a1fd3f0bcafdee9b3db6966addfe2d12ebc65dd48786ba0e07e6339f9062588c6526bcf8427a931aa918b2f99c94b07ce0b8f6a39bf77a2

test:
  secret_key_base: f387b516d912eaa40d74f0ad5089ad8bb4b7a5df6b9c588defec163a4c64c61d1cc149e6937ad72086313def548d852005b386d5eadcebd53e69a35e66910b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
